### PR TITLE
Add deploy

### PR DESCRIPTION
**Pull request by ai**

### CODE REVIEW

**Comment by a-chabin** [comment]
Let's rename `node app.js` to `node index.js`  in `server/package.json`

**Comment by a-chabin** [comment]
Small suggestions after review:
- Rename `Server with client-side hot-reload` → `Server with client-side watcher` in README.md. We haven't hot-reload with page refresh
- Later we will arrange to rename scripts `build:region` → `prebuild:region` . I wrote it in issue https://github.com/browserslist/browsersl.ist/issues/353#issuecomment-1213701632

**Comment by a-chabin** [comment]
We can test `NODE_ENV=production` by running `pnpm ssdeploy run`.

This will be enough?

**Review by a-chabin — APPROVED** [review]

**Comment by a-chabin** [comment]
Thanks for the PR!

P.S. I thought the CI code would be much harder to read. But everything is clear.

**Comment by ai** [comment]
> `build:region` → `prebuild:region`

npm scripts have special logic for all scripts with `pre` prefix.

If you run `a` script, `prea` will be runned before.

**Pull request merged**
